// room2 - procedural mesh module verification.
//
// Checks the contract of src/procgen/mesh.hpp the way the game uses it: the
// room shell, the table, the drinking glass and the pistol are all generated by
// these builders, so topology, winding, normals and UVs must be right for every
// one of them.
//
// Build & run in ONE bash call (/tmp does not persist on this machine):
//   g++ -std=c++20 -O2 -Wall -Wextra -I src tests/mesh_test.cpp src/procgen/mesh.cpp
//       -o build/mesh_test && build/mesh_test
//
// Sections:
//   a. every primitive: non-empty, indices in range, submesh ranges exact
//   b. makeBox({1,1,1}): 24 verts / 36 indices, exact bounds, outward normals
//   c. winding: CCW seen from outside for every convex primitive
//   d. outward normals: uv-sphere and capped cylinder
//   e. watertightness of the closed primitives (2 triangles per welded edge)
//   f. makeBoxInverted world-space UV rate
//   g. makeLathe: bounds, triangle count, closed glass profile
//   h. computeNormals: hard crease stays hard, smooth surface stays smooth
//   i. weld: unique count, unchanged geometry
//   j. degenerate input: no crash, no NaN, consistent bookkeeping
//   k. MeshData helpers: append/merge/addSubMesh/transform/flipWinding/uv tools
//   l. determinism: identical calls produce identical bytes
//   m. surface quality: rounded box distance field, no shading seams

#include "procgen/mesh.hpp"

#include <array>
#include <cmath>
#include <cstdarg>
#include <cstdint>
#include <cstdio>
#include <cstring>
#include <map>
#include <string>
#include <utility>
#include <vector>

using namespace room2;
using namespace room2::procgen;

namespace {

int g_checks = 0;
int g_failures = 0;

std::string fmt(const char* f, ...) {
    char buf[512];
    va_list args;
    va_start(args, f);
    std::vsnprintf(buf, sizeof(buf), f, args);
    va_end(args);
    return std::string(buf);
}

void report(bool ok, const std::string& what, const std::string& detail) {
    ++g_checks;
    if (!ok) ++g_failures;
    std::printf("%s %-54s %s\n", ok ? "[PASS]" : "[FAIL]", what.c_str(), detail.c_str());
}

bool fin3(Vec3 v) { return std::isfinite(v.x) && std::isfinite(v.y) && std::isfinite(v.z); }

// ---------------------------------------------------------------- validators
// Every index references an existing vertex and no attribute is NaN/Inf.
bool meshWellFormed(const MeshData& m, std::string& why) {
    for (size_t i = 0; i < m.vertices.size(); ++i) {
        const Vertex& v = m.vertices[i];
        if (!fin3(v.position)) { why = fmt("vertex %zu position not finite", i); return false; }
        if (!fin3(v.normal)) { why = fmt("vertex %zu normal not finite", i); return false; }
        if (!fin3(v.tangent.xyz()) || !std::isfinite(v.tangent.w)) {
            why = fmt("vertex %zu tangent not finite", i);
            return false;
        }
        if (!std::isfinite(v.uv.x) || !std::isfinite(v.uv.y) || !std::isfinite(v.uv1.x) ||
            !std::isfinite(v.uv1.y)) {
            why = fmt("vertex %zu uv not finite", i);
            return false;
        }
    }
    for (size_t k = 0; k < m.indices.size(); ++k) {
        if (m.indices[k] >= m.vertices.size()) {
            why = fmt("index %zu = %u out of range (%zu verts)", k, m.indices[k], m.vertices.size());
            return false;
        }
    }
    if (m.bounds.valid() && (!fin3(m.bounds.mn) || !fin3(m.bounds.mx))) {
        why = "bounds not finite";
        return false;
    }
    return true;
}

// Submesh ranges: inside the index array, non-overlapping and covering every
// index exactly once.
bool submeshBookkeeping(const MeshData& m, std::string& why) {
    if (m.indices.empty()) {
        if (!m.submeshes.empty()) {
            why = fmt("%zu submeshes for an empty index buffer", m.submeshes.size());
            return false;
        }
        return true;
    }
    if (m.submeshes.empty()) { why = "non-empty mesh without submeshes"; return false; }
    std::vector<int> hits(m.indices.size(), 0);
    for (size_t s = 0; s < m.submeshes.size(); ++s) {
        const SubMesh& sm = m.submeshes[s];
        if (sm.indexCount == 0) { why = fmt("submesh %zu is empty", s); return false; }
        if (sm.indexCount % 3 != 0) {
            why = fmt("submesh %zu count %u not a triangle multiple", s, sm.indexCount);
            return false;
        }
        if (static_cast<size_t>(sm.indexOffset) + sm.indexCount > m.indices.size()) {
            why = fmt("submesh %zu range [%u,%u) outside %zu indices", s, sm.indexOffset,
                      sm.indexOffset + sm.indexCount, m.indices.size());
            return false;
        }
        for (uint32_t k = sm.indexOffset; k < sm.indexOffset + sm.indexCount; ++k) ++hits[k];
    }
    for (size_t k = 0; k < hits.size(); ++k) {
        if (hits[k] != 1) { why = fmt("index %zu covered %d times", k, hits[k]); return false; }
    }
    return true;
}

bool normalsUnit(const MeshData& m, float tol, std::string& why) {
    for (size_t i = 0; i < m.vertices.size(); ++i) {
        const float l = length(m.vertices[i].normal);
        if (std::fabs(l - 1.0f) > tol) { why = fmt("vertex %zu |normal| = %.6f", i, l); return false; }
    }
    return true;
}

// Welds by position only (the primitives duplicate vertices along UV seams, so
// manifoldness is a property of the welded surface).  Tolerance-sized spatial
// grid: a sorted-run weld would split coincident points whenever unrelated
// vertices interleave between them.
std::vector<uint32_t> weldByPosition(const MeshData& m, float tol) {
    const uint32_t n = m.vertexCount();
    std::vector<uint32_t> remap(n, 0);
    if (n == 0) return remap;
    const float cell = max2(tol, 1e-9f);
    const float inv = 1.0f / cell;
    using Cell = std::array<int64_t, 3>;
    auto cellOf = [inv](Vec3 p) {
        return Cell{static_cast<int64_t>(std::floor(p.x * inv)),
                    static_cast<int64_t>(std::floor(p.y * inv)),
                    static_cast<int64_t>(std::floor(p.z * inv))};
    };
    std::map<Cell, std::vector<uint32_t>> grid;  // cell -> welded ids in it
    std::vector<Vec3> reps;
    for (uint32_t i = 0; i < n; ++i) {
        const Vec3 p = m.vertices[i].position;
        const Cell c = cellOf(p);
        int found = -1;
        for (int dz = -1; dz <= 1 && found < 0; ++dz) {
            for (int dy = -1; dy <= 1 && found < 0; ++dy) {
                for (int dx = -1; dx <= 1 && found < 0; ++dx) {
                    const auto it = grid.find(Cell{c[0] + dx, c[1] + dy, c[2] + dz});
                    if (it == grid.end()) continue;
                    for (uint32_t w : it->second) {
                        if (lengthSq(p - reps[w]) <= tol * tol) { found = static_cast<int>(w); break; }
                    }
                }
            }
        }
        if (found < 0) {
            found = static_cast<int>(reps.size());
            reps.push_back(p);
        }
        remap[i] = static_cast<uint32_t>(found);
        grid[c].push_back(static_cast<uint32_t>(found));
    }
    return remap;
}

struct EdgeStats {
    int edges = 0;
    int boundary = 0;    // used by exactly one triangle
    int nonManifold = 0; // used by three or more
    int degenerate = 0;  // collapsed by the weld (zero-area, ignored)
};

EdgeStats edgeStats(const MeshData& m, float tol) {
    EdgeStats st;
    if (m.indices.empty()) return st;
    const std::vector<uint32_t> remap = weldByPosition(m, tol);
    std::map<std::pair<uint32_t, uint32_t>, int> counts;
    for (size_t t = 0; t + 2 < m.indices.size(); t += 3) {
        uint32_t v[3] = {remap[m.indices[t]], remap[m.indices[t + 1]], remap[m.indices[t + 2]]};
        if (v[0] == v[1] || v[1] == v[2] || v[0] == v[2]) { ++st.degenerate; continue; }
        for (int e = 0; e < 3; ++e) {
            uint32_t a = v[e], b = v[(e + 1) % 3];
            if (a > b) std::swap(a, b);
            ++counts[{a, b}];
        }
    }
    st.edges = static_cast<int>(counts.size());
    for (const auto& kv : counts) {
        if (kv.second == 1) ++st.boundary;
        else if (kv.second > 2) ++st.nonManifold;
    }
    return st;
}

struct WindingStats {
    float worst = 1e30f;
    int used = 0;
    int skipped = 0;
    uint32_t worstTri = 0;
};

// For a convex solid and an interior reference point every face must satisfy
// dot(faceNormal, centroid - reference) > 0 when the winding is CCW from outside.
WindingStats windingStats(const MeshData& m, float skipRadius) {
    WindingStats ws;
    const Vec3 c = m.bounds.center();
    for (size_t t = 0; t + 2 < m.indices.size(); t += 3) {
        const Vec3 p0 = m.vertices[m.indices[t]].position;
        const Vec3 p1 = m.vertices[m.indices[t + 1]].position;
        const Vec3 p2 = m.vertices[m.indices[t + 2]].position;
        const Vec3 n = cross(p1 - p0, p2 - p0);
        const Vec3 d = (p0 + p1 + p2) / 3.0f - c;
        if (length(d) < skipRadius) { ++ws.skipped; continue; }
        const float dp = dot(normalize(n), normalize(d));
        ++ws.used;
        if (dp < ws.worst) {
            ws.worst = dp;
            ws.worstTri = static_cast<uint32_t>(t / 3);
        }
    }
    if (ws.used == 0) ws.worst = 0.0f;
    return ws;
}

// Winding check that also holds for non-convex solids (a torus): the geometric
// normal of a CCW triangle must agree with the outward vertex normals it carries.
float worstWindingVsNormals(const MeshData& m) {
    float worst = 1e30f;
    for (size_t t = 0; t + 2 < m.indices.size(); t += 3) {
        const Vertex& a = m.vertices[m.indices[t]];
        const Vertex& b = m.vertices[m.indices[t + 1]];
        const Vertex& c = m.vertices[m.indices[t + 2]];
        const Vec3 fn = normalize(cross(b.position - a.position, c.position - a.position));
        const Vec3 vn = normalize(a.normal + b.normal + c.normal);
        if (lengthSq(fn) < 0.5f || lengthSq(vn) < 0.5f) continue;
        worst = min2(worst, dot(fn, vn));
    }
    return worst == 1e30f ? 0.0f : worst;
}

// The drinking glass from the game: a closed (solid) cross section, CCW in the
// (radius, height) plane, with poles at both bottom centres.
std::vector<Vec2> glassProfile() {
    return {{0.0000f, 0.0000f}, {0.0300f, 0.0000f}, {0.0335f, 0.0060f}, {0.0340f, 0.0130f},
            {0.0340f, 0.0850f}, {0.0330f, 0.0900f}, {0.0320f, 0.0885f}, {0.0305f, 0.0200f},
            {0.0295f, 0.0075f}, {0.0000f, 0.0060f}};
}

// A copy of a profile with its first point repeated at the end, i.e. the way a
// solid cross section is often authored (makeLathe folds the duplicate away).
std::vector<Vec2> withClosingPoint(const std::vector<Vec2>& p) {
    std::vector<Vec2> out(p.size() + 1);
    for (size_t i = 0; i < p.size(); ++i) out[i] = p[i];
    if (!p.empty()) out[p.size()] = p[0];
    return out;
}

// The table's soft edge treatment and the room shell are separate primitives; this
// pole-free open profile is a simple tapered cup wall.
std::vector<Vec2> cupProfile() {
    return {{0.030f, 0.000f}, {0.0335f, 0.012f}, {0.0345f, 0.045f}, {0.0360f, 0.090f}};
}

struct Primitive {
    const char* name;
    MeshData mesh;
    uint32_t material;
    bool closed;  // expected watertight after a position weld
};

std::vector<Primitive> allPrimitives() {
    std::vector<Primitive> v;
    v.push_back({"makeBox", makeBox({1, 1, 1}, {1, 1}, 0), 0, true});
    v.push_back({"makeBox uv2", makeBox({0.7f, 0.02f, 0.45f}, {2, 3}, 4), 4, true});
    v.push_back({"makeBoxInverted", makeBoxInverted({3, 1.5f, 4}, 0.5f, 1), 1, true});
    v.push_back({"makePlane", makePlane(2, 3, 4, 5, 2), 2, false});
    v.push_back({"makeUvSphere", makeUvSphere(1, 32, 16, 3), 3, true});
    v.push_back({"makeCylinder", makeCylinder(0.5f, 2, 32, true, 5), 5, true});
    v.push_back({"makeCylinder open", makeCylinder(0.5f, 2, 24, false, 5), 5, false});
    v.push_back({"makeCone", makeCone(0.6f, 1.4f, 32, 6), 6, true});
    v.push_back({"makeCapsule", makeCapsule(0.35f, 1.0f, 32, 8, 7), 7, true});
    v.push_back({"makeTorus", makeTorus(1, 0.35f, 48, 24, 8), 8, true});
    v.push_back({"makeRoundedBox", makeRoundedBox({0.6f, 0.25f, 0.4f}, 0.06f, 4, 9), 9, false});
    v.push_back({"makeRoundedBox soft", makeRoundedBox({0.7f, 0.02f, 0.45f}, 0.015f, 3, 10), 10, false});
    v.push_back({"makeLathe glass", makeLathe(glassProfile(), 48, 11), 11, true});
    v.push_back({"makeLathe cup", makeLathe(cupProfile(), 24, 12), 12, false});
    v.push_back({"makeFullscreenTriangle", makeFullscreenTriangle(), 0, false});
    return v;
}

// ============================================================ a: primitives
void testA() {
    std::vector<Primitive> prims = allPrimitives();
    int bad = 0;
    std::printf("\n-- per-primitive counts --------------------------------------------------\n");
    for (Primitive& p : prims) {
        std::string why;
        bool ok = !p.mesh.empty() && p.mesh.triangleCount() > 0;
        if (!ok) why = "empty mesh";
        if (ok && !meshWellFormed(p.mesh, why)) ok = false;
        if (ok && !submeshBookkeeping(p.mesh, why)) ok = false;
        if (ok && !p.mesh.bounds.valid()) { ok = false; why = "invalid bounds"; }
        if (ok && !normalsUnit(p.mesh, 1e-3f, why)) ok = false;
        if (ok && p.mesh.submeshes.size() != 1) {
            ok = false;
            why = fmt("%zu submeshes", p.mesh.submeshes.size());
        }
        if (ok && p.mesh.submeshes[0].material != p.material) {
            ok = false;
            why = fmt("material %u != %u", p.mesh.submeshes[0].material, p.material);
        }
        if (ok) {
            std::printf("   %-22s verts %6u  tris %6u  submesh[0] mat %u\n", p.name, p.mesh.vertexCount(),
                        p.mesh.triangleCount(), p.mesh.submeshes[0].material);
        } else {
            ++bad;
            std::printf("   %-22s INVALID: %s\n", p.name, why.c_str());
        }
    }
    std::printf("-------------------------------------------------------------------------\n");
    report(bad == 0, "a. every primitive is well formed",
           fmt("%zu primitives, %d invalid, all indices in range, submeshes cover each index once",
               prims.size(), bad));
}

// ============================================================ b: box
void testB() {
    const MeshData b = makeBox({1, 1, 1});
    bool ok = b.vertexCount() == 24 && b.indexCount() == 36 && b.triangleCount() == 12;
    std::string why = fmt("verts %u, indices %u, tris %u (want 24/36/12)", b.vertexCount(), b.indexCount(),
                          b.triangleCount());
    report(ok, "b. makeBox({1,1,1}) is 24 verts / 36 indices", why);

    const bool boundsExact = b.bounds.mn.x == -1.0f && b.bounds.mn.y == -1.0f && b.bounds.mn.z == -1.0f &&
                             b.bounds.mx.x == 1.0f && b.bounds.mx.y == 1.0f && b.bounds.mx.z == 1.0f;
    report(boundsExact, "b. makeBox bounds are exactly [-1,-1,-1]..[1,1,1]",
           fmt("mn (%.1f,%.1f,%.1f) mx (%.1f,%.1f,%.1f)", b.bounds.mn.x, b.bounds.mn.y, b.bounds.mn.z,
               b.bounds.mx.x, b.bounds.mx.y, b.bounds.mx.z));

    int bad = 0;
    float worst = 1.0f;
    for (uint32_t i = 0; i < b.vertexCount(); ++i) {
        const Vertex& v = b.vertices[i];
        int axis = 0;
        for (int a = 1; a < 3; ++a) {
            if (std::fabs(v.normal[a]) > std::fabs(v.normal[axis])) axis = a;
        }
        // Dominant normal axis must be unit length and point the same way as the
        // face offset of the vertex.
        const bool unit = std::fabs(std::fabs(v.normal[axis]) - 1.0f) < 1e-5f;
        const bool outward = v.position[axis] * v.normal[axis] > 0.0f;
        if (!unit || !outward) ++bad;
        worst = min2(worst, v.position[axis] * v.normal[axis]);
    }
    report(bad == 0, "b. every box normal points away from the origin",
           fmt("%d bad vertices, worst position*normal on dominant axis %.3f", bad, worst));
}

// ============================================================ c: winding
void testC() {
    struct Case {
        const char* name;
        MeshData mesh;
        bool convex;  // torus is the one non-convex solid in this list
    };
    std::vector<Case> cases;
    cases.push_back({"makeBox", makeBox({1, 1, 1}), true});
    cases.push_back({"makeUvSphere", makeUvSphere(1, 32, 16), true});
    cases.push_back({"makeCylinder capped", makeCylinder(0.5f, 2, 32, true), true});
    cases.push_back({"makeCone", makeCone(0.6f, 1.4f, 32), true});
    cases.push_back({"makeCapsule", makeCapsule(0.35f, 1.0f, 32, 8), true});
    cases.push_back({"makeTorus", makeTorus(1, 0.35f, 48, 24), false});
    // Lathe of a convex (half-ellipse) profile: 7 points, poles at both ends.
    std::vector<Vec2> lens;
    for (int k = 0; k <= 6; ++k) {
        const float t = static_cast<float>(k) * PI / 6.0f;
        lens.push_back(Vec2(std::sin(t), -std::cos(t)));
    }
    cases.push_back({"makeLathe (convex)", makeLathe(lens, 32), true});

    int bad = 0;
    float worstConvex = 1e30f, worstAny = 1e30f;
    for (Case& c : cases) {
        const WindingStats ws = windingStats(c.mesh, 1e-4f);
        const float vn = worstWindingVsNormals(c.mesh);
        const bool ok = vn > 0.0f && (!c.convex || ws.worst > 0.0f);
        if (!ok) ++bad;
        if (c.convex) worstConvex = min2(worstConvex, ws.worst);
        worstAny = min2(worstAny, vn);
        std::printf("   %-22s tris %6u  %s min dot(n, c-centre) %+.5f   min dot(faceN, vertexN) %+.5f\n",
                    c.name, c.mesh.triangleCount(), c.convex ? "convex " : "(hollow)", ws.worst, vn);
    }
    report(bad == 0, "c. every primitive is CCW seen from outside",
           fmt("%zu primitives, %d inward, convex centroid test worst dot %+.5f, face/vertex normal "
               "agreement worst dot %+.5f (the torus is non-convex, so the centroid criterion does not "
               "apply to it and its winding is verified against the outward vertex normals)",
               cases.size(), bad, worstConvex, worstAny));
}

// ============================================================ d: outward normals
void testD() {
    // ---- uv sphere: normal == normalize(position - centre).
    const MeshData s = makeUvSphere(1, 32, 16);
    float minSphere = 1e30f;
    for (const Vertex& v : s.vertices) {
        minSphere = min2(minSphere, dot(v.normal, normalize(v.position)));
    }
    report(minSphere > 0.9f, "d. uv-sphere normals point away from the centre",
           fmt("min dot(normal, normalize(position - centre)) = %.6f over %u vertices", minSphere,
               s.vertexCount()));

    // ---- capped cylinder: side vertices are radial, cap vertices are axis aligned.
    const MeshData c = makeCylinder(0.5f, 2, 32, true);
    float minSide = 1e30f;
    int side = 0, cap = 0, capBad = 0;
    for (const Vertex& v : c.vertices) {
        if (std::fabs(v.normal.y) < 0.5f) {
            const Vec3 axisPoint(0.0f, v.position.y, 0.0f);
            minSide = min2(minSide, dot(v.normal, normalize(v.position - axisPoint)));
            ++side;
        } else {
            ++cap;
            if (std::fabs(v.normal.y) < 0.999f) ++capBad;
            if (v.normal.y * v.position.y <= 0.0f) ++capBad;
        }
    }
    const bool ok = side > 0 && cap > 0 && minSide > 0.9f && capBad == 0;
    report(ok, "d. cylinder side normals radial, cap normals axis aligned",
           fmt("min side dot = %.6f (%d side verts), %d cap verts, %d bad caps", minSide, side, cap,
               capBad));
}

// ============================================================ e: watertightness
void testE() {
    std::vector<Primitive> prims = allPrimitives();
    int bad = 0, closedCount = 0;
    for (Primitive& p : prims) {
        if (!p.closed) continue;
        ++closedCount;
        const EdgeStats st = edgeStats(p.mesh, 1e-5f);
        const bool ok = st.boundary == 0 && st.nonManifold == 0 && st.degenerate == 0;
        if (!ok) ++bad;
        std::printf("   %-22s edges %5d  boundary %d  non-manifold %d  degenerate %d  %s\n", p.name,
                    st.edges, st.boundary, st.nonManifold, st.degenerate, ok ? "closed" : "NOT CLOSED");
    }
    report(bad == 0, "e. closed primitives are watertight after a 1e-5 weld",
           fmt("%d closed primitives checked, %d with boundary/non-manifold edges", closedCount, bad));
}

// ============================================================ f: room shell UVs
void testF() {
    const float uvScale = 0.5f;
    const MeshData room = makeBoxInverted({3, 1.5f, 4}, uvScale, 2);
    const float tol = 1e-4f;
    int checked = 0, badTri = 0, badPlanar = 0;
    int axisSeen[3][2] = {{0, 0}, {0, 0}, {0, 0}};
    std::string firstBad;
    for (size_t t = 0; t + 2 < room.indices.size(); t += 3) {
        const Vertex& a = room.vertices[room.indices[t]];
        const Vertex& b = room.vertices[room.indices[t + 1]];
        const Vertex& c = room.vertices[room.indices[t + 2]];
        const Vec3 n = cross(b.position - a.position, c.position - a.position);
        const float nl = length(n);
        if (nl < 1e-9f) continue;
        int dom = 0;
        for (int k = 1; k < 3; ++k) {
            if (std::fabs(n[k]) > std::fabs(n[dom])) dom = k;
        }
        // Wall must be axis aligned, and the outward side of the shell is -n here
        // (inverted box), so the dominant axis is the wall's axis in both signs.
        for (int k = 0; k < 3; ++k) {
            if (k != dom && std::fabs(n[k]) > 1e-4f * nl) ++badPlanar;
        }
        axisSeen[dom][n[dom] > 0.0f ? 0 : 1] = 1;
        ++checked;
        // u and v must each equal +/-world[axis] * uvScale on the whole triangle.
        for (int channel = 0; channel < 2; ++channel) {
            bool found = false;
            for (int k = 0; k < 3 && !found; ++k) {
                for (int sign = 0; sign < 2 && !found; ++sign) {
                    const float sg = sign == 0 ? 1.0f : -1.0f;
                    const float da = (channel == 0 ? a.uv.x : a.uv.y) - sg * a.position[k] * uvScale;
                    const float db = (channel == 0 ? b.uv.x : b.uv.y) - sg * b.position[k] * uvScale;
                    const float dc = (channel == 0 ? c.uv.x : c.uv.y) - sg * c.position[k] * uvScale;
                    if (std::fabs(da) < tol && std::fabs(db) < tol && std::fabs(dc) < tol) found = true;
                }
            }
            if (!found) {
                ++badTri;
                if (firstBad.empty()) {
                    firstBad = fmt("tri %zu channel %d (u = %.4f/%.4f/%.4f, p0 = %.3f,%.3f,%.3f)", t / 3,
                                   channel, a.uv.x + 0.0f * b.uv.x, b.uv.x, c.uv.x, a.position.x,
                                   a.position.y, a.position.z);
                }
            }
        }
    }
    int axes = 0;
    for (int k = 0; k < 3; ++k) axes += axisSeen[k][0] + axisSeen[k][1];
    const bool ok = checked > 0 && badTri == 0 && badPlanar == 0 && axes == 6;
    report(ok, "f. makeBoxInverted UVs are world space at the requested rate",
           fmt("%d tris, %d bad uv, %d non-planar, %d/6 wall axes, rate %.3f%s", checked, badTri,
               badPlanar, axes, static_cast<double>(uvScale),
               firstBad.empty() ? "" : (" first bad: " + firstBad).c_str()));
}

// ============================================================ g: lathe
void testG() {
    // ---- open, pole free cup wall: exact triangle count and exact bounds.
    const std::vector<Vec2> cup = cupProfile();
    const int segs = 32;
    const MeshData a = makeLathe(cup, segs, 3);
    const uint32_t wantTris = static_cast<uint32_t>(segs * (static_cast<int>(cup.size()) - 1) * 2);
    const bool countOk = a.triangleCount() == wantTris;
    report(countOk, "g. makeLathe open profile triangle count",
           fmt("tris %u == segments*(points-1)*2 = %u", a.triangleCount(), wantTris));

    float maxR = 0.0f, minY = 1e30f, maxY = -1e30f;
    for (const Vec2& p : cup) {
        maxR = max2(maxR, p.x);
        minY = min2(minY, p.y);
        maxY = max2(maxY, p.y);
    }
    const Vec3 wantMn(-maxR, minY, -maxR), wantMx(maxR, maxY, maxR);
    const float e = max2(max2(std::fabs(a.bounds.mn.x - wantMn.x), std::fabs(a.bounds.mn.y - wantMn.y)),
                         max2(std::fabs(a.bounds.mx.x - wantMx.x), std::fabs(a.bounds.mx.y - wantMx.y)));
    const std::string why = fmt("bounds err %.2e (mn %.4f,%.4f,%.4f mx %.4f,%.4f,%.4f)", e, a.bounds.mn.x,
                                a.bounds.mn.y, a.bounds.mn.z, a.bounds.mx.x, a.bounds.mx.y, a.bounds.mx.z);
    report(e < 1e-4f, "g. makeLathe bounds match the profile extents", why);

    // The rendered cup must also be wound outwards with radial normals.
    const WindingStats ws = windingStats(a, 1e-4f);
    float minRadial = 1e30f;
    for (const Vertex& v : a.vertices) {
        minRadial = min2(minRadial, dot(v.normal, normalize(Vec3(v.position.x, 0.0f, v.position.z))));
    }
    report(ws.worst > 0.0f && minRadial > 0.9f, "g. makeLathe cup is CCW with outward normals",
           fmt("min winding dot %+.5f, min radial dot %.5f", ws.worst, minRadial));

    // ---- the actual drinking glass: closed profile with poles and a crisp rim.
    const std::vector<Vec2> glass = glassProfile();
    const MeshData g = makeLathe(glass, 48, 11);
    const EdgeStats es = edgeStats(g, 1e-5f);
    // 10 profile points form 9 bands, two of which touch a pole (one tri per
    // segment there): 7*2*48 + 2*48 triangles.
    const uint32_t wantGlass = static_cast<uint32_t>(7 * 2 * 48 + 2 * 48);
    const float glassMaxR = 0.0340f;
    const bool glassOk = g.triangleCount() == wantGlass && es.boundary == 0 && es.nonManifold == 0 &&
                         es.degenerate == 0 && std::fabs(g.bounds.mx.x - glassMaxR) < 1e-4f &&
                         std::fabs(g.bounds.mn.y - 0.0f) < 1e-4f && std::fabs(g.bounds.mx.y - 0.09f) < 1e-4f;
    report(glassOk, "g. makeLathe glass is watertight with the expected size",
           fmt("tris %u (want %u), boundary %d, non-manifold %d, degenerate %d, bounds x %.4f y %.4f..%.4f",
               g.triangleCount(), wantGlass, es.boundary, es.nonManifold, es.degenerate, g.bounds.mx.x,
               g.bounds.mn.y, g.bounds.mx.y));

    // ---- closed profile detection: the glass loop is stored with the duplicate
    // closing point, which must be folded away instead of creating a seam band.
    const MeshData g2 = makeLathe(withClosingPoint(glass), 48, 11);
    report(g2.vertexCount() == g.vertexCount() && g2.indexCount() == g.indexCount(),
           "g. makeLathe drops a duplicated closing profile point",
           fmt("closed copy: verts %u/%u indices %u/%u", g2.vertexCount(), g.vertexCount(), g2.indexCount(),
               g.indexCount()));

    // ---- a CCW square tube profile exercises the closed path with no poles.
    const std::vector<Vec2> tube = {{1.0f, -1.0f}, {1.5f, -1.0f}, {1.5f, 1.0f}, {1.0f, 1.0f}};
    const MeshData t = makeLathe(withClosingPoint(tube), 24, 0);
    const EdgeStats ts = edgeStats(t, 1e-5f);
    report(t.triangleCount() == 4u * 24u * 2u && ts.boundary == 0 && ts.nonManifold == 0,
           "g. makeLathe closed tube profile is a watertight ring",
           fmt("tris %u (want %u), boundary %d, non-manifold %d", t.triangleCount(), 4u * 24u * 2u,
               ts.boundary, ts.nonManifold));
}

// ============================================================ h: computeNormals
void testH() {
    // ---- 90 degree crease between two quads that only touch along an edge.
    MeshData m;
    const Vec3 pos[8] = {{-1, 0, -1}, {-1, 0, 1}, {0, 0, 1},  {0, 0, -1},
                         {0, 0, -1},  {0, 0, 1},  {0, 1, 1},  {0, 1, -1}};
    for (int i = 0; i < 8; ++i) {
        Vertex v;
        v.position = pos[i];
        v.normal = Vec3(0.577f, 0.577f, 0.577f);  // deliberately wrong on purpose
        v.tangent = Vec4(1, 0, 0, 1);
        v.uv = Vec2(0, 0);
        v.uv1 = Vec2(0, 0);
        m.vertices.push_back(v);
    }
    m.indices = {0, 1, 2, 0, 2, 3, 4, 5, 6, 4, 6, 7};
    m.addSubMesh(0, 0, "crease");
    m.computeBounds();
    m.computeNormals(40.0f);
    float worstFlat = 1.0f, worstVert = 1.0f;
    for (int i = 0; i < 8; ++i) {
        const Vec3 want = i < 4 ? Vec3(0, 1, 0) : Vec3(-1, 0, 0);
        const float d = dot(m.vertices[i].normal, want);
        if (i < 4) worstFlat = min2(worstFlat, d);
        else worstVert = min2(worstVert, d);
    }
    // The two sides of the crease must keep distinct normals.
    const float creaseDot = dot(m.vertices[3].normal, m.vertices[7].normal);
    report(worstFlat > 0.999f && worstVert > 0.999f && creaseDot < 0.5f,
           "h. computeNormals keeps a 90 degree crease hard",
           fmt("horizontal side dot %.6f, vertical side dot %.6f, crease dot %.6f",
               static_cast<double>(worstFlat), static_cast<double>(worstVert),
               static_cast<double>(creaseDot)));

    // ---- the same call on a sphere must smooth everything, including the
    // duplicated UV seam columns and the poles.
    MeshData s = makeUvSphere(1, 32, 16);
    for (Vertex& v : s.vertices) v.normal = Vec3(0.2f, -0.5f, 0.84f);
    s.computeNormals(40.0f);
    float minDot = 1e30f;
    uint32_t worst = 0;
    for (uint32_t i = 0; i < s.vertexCount(); ++i) {
        const float d = dot(s.vertices[i].normal, normalize(s.vertices[i].position));
        if (d < minDot) {
            minDot = d;
            worst = i;
        }
    }
    report(minDot > 0.999f, "h. computeNormals smooths a sphere",
           fmt("min dot(normal, normalize(position)) = %.6f (vertex %u of %u)", minDot, worst,
               s.vertexCount()));
}

// ============================================================ i: weld
void testI() {
    const MeshData base = makeUvSphere(1, 24, 12);
    MeshData d = base;
    d.append(base);  // every vertex duplicated, triangle count doubled
    const uint32_t before = d.vertexCount();
    const uint32_t trisBefore = d.triangleCount();
    const Aabb boundsBefore = d.bounds;
    d.weld(1e-6f);
    const bool counts = d.vertexCount() == base.vertexCount() && d.triangleCount() == trisBefore;
    const float boundsErr = max2(max2(std::fabs(d.bounds.mn.x - boundsBefore.mn.x),
                                      std::fabs(d.bounds.mn.y - boundsBefore.mn.y)),
                                 max2(std::fabs(d.bounds.mx.x - boundsBefore.mx.x),
                                      std::fabs(d.bounds.mx.y - boundsBefore.mx.y)));
    std::string why;
    const bool ok = counts && boundsErr < 1e-6f && meshWellFormed(d, why) &&
                    submeshBookkeeping(d, why);
    report(ok, "i. weld halves a duplicated mesh without touching geometry",
           fmt("verts %u -> %u (unique %u), tris %u -> %u, bounds delta %.1e%s", before, d.vertexCount(),
               base.vertexCount(), trisBefore, d.triangleCount(), static_cast<double>(boundsErr),
               ok ? "" : (" " + why).c_str()));

    // Welding must not merge across a UV seam or a hard crease: a box stays 24.
    MeshData b = makeBox({1, 1, 1});
    MeshData b2 = b;
    b2.append(b);
    b2.weld(1e-6f);
    report(b2.vertexCount() == 24, "i. weld keeps crease/UV split vertices apart",
           fmt("box verts after welding a duplicate copy: %u (want 24)", b2.vertexCount()));
}

// ============================================================ j: degenerate input
void testJ() {
    std::vector<Primitive> bad;
    bad.push_back({"box zero", makeBox({0, 0, 0}), 0, false});
    bad.push_back({"box negative", makeBox({-1, -2, -3}), 0, false});
    bad.push_back({"box nan uv", makeBox({1, 1, 1}, Vec2(0.0f, 0.0f) * (0.0f / 0.0f)), 0, false});
    bad.push_back({"room zero", makeBoxInverted({0, 0, 0}, 0.0f), 0, false});
    bad.push_back({"room negative", makeBoxInverted({-3, -1.5f, -4}, -2.0f, 7), 7, false});
    bad.push_back({"plane zero", makePlane(0, 0, 0, 0), 0, false});
    bad.push_back({"plane negative", makePlane(-1, -1, -5, -5), 0, false});
    bad.push_back({"sphere zero", makeUvSphere(0, 0, 0), 0, false});
    bad.push_back({"sphere 1 seg", makeUvSphere(-1, 1, 1), 0, false});
    bad.push_back({"cylinder zero", makeCylinder(0, 0, 0, true), 0, false});
    bad.push_back({"cylinder 1 seg", makeCylinder(-2, -2, 1, false), 0, false});
    bad.push_back({"cone zero", makeCone(0, 0, 0), 0, false});
    bad.push_back({"cone 1 seg", makeCone(-0.5f, -1.0f, 1), 0, false});
    bad.push_back({"capsule zero", makeCapsule(0, 0, 0, 0), 0, false});
    bad.push_back({"capsule flat", makeCapsule(0.5f, 0.0f, 8, 2), 0, false});
    bad.push_back({"torus zero", makeTorus(0, 0, 0, 0), 0, false});
    bad.push_back({"torus 1 seg", makeTorus(-1, -1, 1, 1), 0, false});
    bad.push_back({"lathe empty", makeLathe({}, 0), 0, false});
    bad.push_back({"lathe 1 point", makeLathe({{0, 0}}, 0), 0, false});
    bad.push_back({"lathe axis only", makeLathe({{0, 0}, {0, 1}}, 1), 0, false});
    bad.push_back({"lathe dup points", makeLathe({{1, 0}, {1, 0}, {1, 1}, {1, 1}}, -4), 0, false});
    bad.push_back({"lathe negative r", makeLathe({{-1, 0}, {-1, 1}}, 3), 0, false});
    bad.push_back({"roundedbox zero", makeRoundedBox({0, 0, 0}, 0, 0), 0, false});
    bad.push_back({"roundedbox negative", makeRoundedBox({-1, -1, -1}, -0.5f, -3), 0, false});
    bad.push_back({"roundedbox big r", makeRoundedBox({1, 1, 1}, 10.0f, 4), 0, false});
    bad.push_back({"fullscreen", makeFullscreenTriangle(), 0, false});

    int badCount = 0;
    for (Primitive& p : bad) {
        std::string why;
        bool ok = meshWellFormed(p.mesh, why);
        if (ok && !submeshBookkeeping(p.mesh, why)) ok = false;
        if (ok && p.mesh.submeshes.size() > 1) { ok = false; why = "more than one submesh"; }
        if (!ok) {
            ++badCount;
            std::printf("   %-22s INVALID: %s\n", p.name, why.c_str());
        }
    }
    report(badCount == 0, "j. degenerate input never crashes and stays consistent",
           fmt("%zu degenerate calls, %d inconsistent results, all finite and fully booked", bad.size(),
               badCount));

    // A capsule with a zero cylinder height must still be a closed sphere-ish solid.
    const MeshData cap = makeCapsule(0.5f, 0.0f, 16, 6);
    const EdgeStats es = edgeStats(cap, 1e-5f);
    report(es.boundary == 0 && es.nonManifold == 0 && es.degenerate == 0 && cap.triangleCount() > 0,
           "j. capsule with zero cylinder height is a closed sphere",
           fmt("tris %u, boundary %d, non-manifold %d, bounds y %.3f..%.3f", cap.triangleCount(),
               es.boundary, es.nonManifold, cap.bounds.mn.y, cap.bounds.mx.y));
}

// ============================================================ k: MeshData helpers
void testK() {
    // ---- append offsets indices and submesh ranges.
    MeshData a = makeBox({1, 1, 1}, {1, 1}, 0);
    const MeshData b = makeUvSphere(0.5f, 8, 4, 5);
    const uint32_t av = a.vertexCount(), ai = a.indexCount();
    a.append(b, 3);
    const bool appendOk = a.vertexCount() == av + b.vertexCount() &&
                          a.indexCount() == ai + b.indexCount() && a.submeshes.size() == 2 &&
                          a.submeshes[1].indexOffset == ai && a.submeshes[1].material == 8 &&
                          a.bounds.overlaps(b.bounds) && a.bounds.contains(b.bounds.mx);
    std::string why;
    report(appendOk && submeshBookkeeping(a, why), "k. append offsets indices, materials and bounds",
           fmt("verts %u, indices %u, submeshes %zu (mat %u at %u)", a.vertexCount(), a.indexCount(),
               a.submeshes.size(), a.submeshes[1].material, a.submeshes[1].indexOffset));

    // ---- addSubMesh closes the range [firstIndex, end) of the index buffer.
    MeshData raw = makeBox({1, 1, 1});
    raw.submeshes.clear();
    raw.addSubMesh(0, 12, "closed");
    const bool addOk = raw.submeshes.size() == 1 && raw.submeshes[0].indexOffset == 0 &&
                       raw.submeshes[0].indexCount == raw.indexCount() &&
                       raw.submeshes[0].material == 12 && raw.submeshes[0].name == "closed" &&
                       raw.submeshes[0].bounds.valid() && submeshBookkeeping(raw, why);
    report(addOk, "k. addSubMesh closes a range with the requested material",
           fmt("submesh [%u,%u) material %u, coverage of every index once: %s",
               raw.submeshes[0].indexOffset, raw.submeshes[0].indexOffset + raw.submeshes[0].indexCount,
               raw.submeshes[0].material, addOk ? "yes" : "no"));
    MeshData tail = makeBox({1, 1, 1});
    tail.submeshes.clear();
    tail.addSubMesh(18, 13, "tail");
    report(tail.submeshes.size() == 1 && tail.submeshes[0].indexOffset == 18 &&
               tail.submeshes[0].indexCount == 18 && tail.submeshes[0].material == 13,
           "k. addSubMesh starts at firstIndex",
           fmt("submesh [%u,%u) material %u (want [18,36) material 13)", tail.submeshes[0].indexOffset,
               tail.submeshes[0].indexOffset + tail.submeshes[0].indexCount, tail.submeshes[0].material));

    // ---- mergeSubMeshes collapses everything into one range.
    a.mergeSubMeshes(21, "merged");
    const bool mergeOk = a.submeshes.size() == 1 && a.submeshes[0].indexOffset == 0 &&
                         a.submeshes[0].indexCount == a.indexCount() && a.submeshes[0].material == 21 &&
                         a.submeshes[0].name == "merged" && a.submeshes[0].bounds.valid();
    report(mergeOk, "k. mergeSubMeshes produces one full-range submesh",
           fmt("%zu submesh, [0,%u) material %u", a.submeshes.size(), a.submeshes[0].indexCount,
               a.submeshes[0].material));

    // ---- transform: scale, mirror and rotate keep normals unit and winding outward.
    MeshData box = makeBox({1, 1, 1});
    const MeshData boxCopy = box;
    box.transform(mat4Scale(Vec3(2, 3, 4)));
    const bool scaleOk = std::fabs(box.bounds.mx.x - 2.0f) < 1e-5f &&
                         std::fabs(box.bounds.mx.y - 3.0f) < 1e-5f &&
                         std::fabs(box.bounds.mx.z - 4.0f) < 1e-5f &&
                         std::fabs(box.bounds.mn.y + 3.0f) < 1e-5f;
    report(scaleOk, "k. transform scales positions and recomputes bounds",
           fmt("bounds mx (%.3f,%.3f,%.3f)", box.bounds.mx.x, box.bounds.mx.y, box.bounds.mx.z));

    MeshData mirrored = boxCopy;
    mirrored.transform(mat4Scale(Vec3(-1, 1, 1)));
    const WindingStats mw = windingStats(mirrored, 1e-4f);
    float minOut = 1e30f;
    for (const Vertex& v : mirrored.vertices) minOut = min2(minOut, dot(v.normal, normalize(v.position)));
    report(mw.worst > 0.0f && minOut > 0.5f, "k. transform flips winding for mirrored transforms",
           fmt("min winding dot %+.5f, min outward dot %.5f", mw.worst, minOut));

    MeshData moved = boxCopy;
    const Mat4 t = mat4Translate(Vec3(10, -2, 3));
    moved.transform(t);
    const bool moveOk = std::fabs(moved.bounds.center().x - 10.0f) < 1e-5f &&
                        std::fabs(moved.bounds.center().y + 2.0f) < 1e-5f &&
                        std::fabs(moved.bounds.center().z - 3.0f) < 1e-5f;
    report(moveOk, "k. transform applies translation to every vertex",
           fmt("centre (%.3f,%.3f,%.3f)", moved.bounds.center().x, moved.bounds.center().y,
               moved.bounds.center().z));

    // ---- flipWinding mirrors the faces and is its own inverse.
    MeshData flipped = boxCopy;
    flipped.flipWinding();
    const WindingStats fw = windingStats(flipped, 1e-4f);
    float maxOut = -1e30f;
    for (const Vertex& v : flipped.vertices) maxOut = max2(maxOut, dot(v.normal, normalize(v.position)));
    flipped.flipWinding();
    const bool byteIdentical =
        flipped.vertices.size() == boxCopy.vertices.size() &&
        std::memcmp(flipped.vertices.data(), boxCopy.vertices.data(),
                    boxCopy.vertices.size() * sizeof(Vertex)) == 0 &&
        flipped.indices == boxCopy.indices;
    report(fw.worst < 0.0f && maxOut < 0.0f && byteIdentical,
           "k. flipWinding inverts faces and normals, twice restores the mesh",
           fmt("flipped min dot %+.5f, max outward dot %+.5f, double flip identical: %s", fw.worst, maxOut,
               byteIdentical ? "yes" : "no"));

    // ---- UV helpers.
    MeshData uv = makeBox({1, 1, 1});
    const Vec2 uv0 = uv.vertices[0].uv;
    scaleUv(uv, Vec2(2, 3));
    offsetUv(uv, Vec2(-1, 0.5f));
    const bool uvOk = std::fabs(uv.vertices[0].uv.x - (uv0.x * 2.0f - 1.0f)) < 1e-6f &&
                      std::fabs(uv.vertices[0].uv.y - (uv0.y * 3.0f + 0.5f)) < 1e-6f &&
                      std::fabs(uv.vertices[0].uv1.x - uv.vertices[0].uv.x) < 1e-6f;
    report(uvOk, "k. scaleUv/offsetUv transform uv and uv1",
           fmt("uv0 (%.3f,%.3f) -> (%.3f,%.3f)", uv0.x, uv0.y, uv.vertices[0].uv.x, uv.vertices[0].uv.y));

    MeshData proj = makeBox({1, 0.5f, 2});
    boxProjectUv(proj, 4.0f);
    // Box projection must map every vertex onto two world axes at the given rate.
    int projBad = 0;
    for (const Vertex& v : proj.vertices) {
        bool uOk = false, vOk = false;
        for (int k = 0; k < 3; ++k) {
            if (std::fabs(std::fabs(v.uv.x) - std::fabs(v.position[k]) * 4.0f) < 1e-4f) uOk = true;
            if (std::fabs(std::fabs(v.uv.y) - std::fabs(v.position[k]) * 4.0f) < 1e-4f) vOk = true;
        }
        if (!uOk || !vOk) ++projBad;
    }
    report(projBad == 0, "k. boxProjectUv unwraps in world units at the requested scale",
           fmt("%d/%u vertices off the box projection", projBad, proj.vertexCount()));

    // ---- fixSeamNormals averages the two duplicated seam columns of a revolution.
    MeshData cyl = makeCylinder(0.5f, 2, 32, true);
    for (Vertex& v : cyl.vertices) {
        if (v.uv.x < 1e-6f) v.normal = normalize(v.normal + Vec3(0.25f, 0, 0));
        if (v.uv.x > 1.0f - 1e-6f) v.normal = normalize(v.normal + Vec3(0, 0, 0.25f));
    }
    fixSeamNormals(cyl, 32);
    float seamDot = 1.0f, seamRadial = 1.0f;
    int pairs = 0;
    for (uint32_t i = 0; i < cyl.vertexCount(); ++i) {
        const Vertex& a = cyl.vertices[i];
        if (a.uv.x > 1e-6f || std::fabs(a.normal.y) > 0.5f) continue;  // side wall only
        for (uint32_t j = 0; j < cyl.vertexCount(); ++j) {
            const Vertex& b = cyl.vertices[j];
            if (b.uv.x < 1.0f - 1e-6f || std::fabs(b.normal.y) > 0.5f) continue;
            if (lengthSq(a.position - b.position) > 1e-10f) continue;
            ++pairs;
            seamDot = min2(seamDot, dot(a.normal, b.normal));
            seamRadial = min2(seamRadial, dot(a.normal, normalize(Vec3(a.position.x, 0, a.position.z))));
        }
    }
    report(pairs > 0 && seamDot > 0.999f && seamRadial > 0.9f, "k. fixSeamNormals merges the seam columns",
           fmt("%d seam pairs, min seam dot %.6f, min radial dot %.6f", pairs, seamDot, seamRadial));

    // ---- free function computeBounds == MeshData::computeBounds.
    const Aabb fb = computeBounds(cyl.vertices);
    const Aabb mb = cyl.bounds;
    report(std::fabs(fb.mn.x - mb.mn.x) < 1e-9f && std::fabs(fb.mx.z - mb.mx.z) < 1e-9f,
           "k. computeBounds matches MeshData::computeBounds",
           fmt("mn (%.4f,%.4f,%.4f) mx (%.4f,%.4f,%.4f)", fb.mn.x, fb.mn.y, fb.mn.z, fb.mx.x, fb.mx.y,
               fb.mx.z));
}

// ============================================================ l: determinism
void testL() {
    const std::vector<Vec2> glass = glassProfile();
    MeshData a = makeLathe(glass, 48, 3);
    MeshData b = makeLathe(glass, 48, 3);
    const bool same = a.vertices.size() == b.vertices.size() && a.indices == b.indices &&
                      a.submeshes.size() == b.submeshes.size() &&
                      std::memcmp(a.vertices.data(), b.vertices.data(),
                                  a.vertices.size() * sizeof(Vertex)) == 0 &&
                      std::memcmp(&a.bounds, &b.bounds, sizeof(Aabb)) == 0;
    MeshData c = makeUvSphere(1, 32, 16);
    c.computeNormals(40.0f);
    MeshData d = makeUvSphere(1, 32, 16);
    d.computeNormals(40.0f);
    const bool same2 = c.vertices.size() == d.vertices.size() &&
                       std::memcmp(c.vertices.data(), d.vertices.data(),
                                   c.vertices.size() * sizeof(Vertex)) == 0;
    report(same && same2, "l. identical calls produce byte-identical meshes",
           fmt("lathe %u verts / %u indices and computeNormals output both identical", a.vertexCount(),
               a.indexCount()));
}

// ============================================================ m: surface quality
// Details the PBR pass depends on: exact rounded-box distance field, and no
// shading seam where a primitive duplicates vertices along a UV seam.
void testM() {
    // ---- rounded box: every vertex sits exactly cornerRadius away from the inner
    // box, and its normal is that offset direction (the SDF gradient).
    const Vec3 he(0.6f, 0.25f, 0.4f);
    const float r = 0.06f;
    const MeshData rb = makeRoundedBox(he, r, 4);
    const Vec3 inner(he.x - r, he.y - r, he.z - r);
    float maxDistErr = 0.0f, maxNormalErr = 0.0f;
    for (const Vertex& v : rb.vertices) {
        const Vec3 q(clamp(v.position.x, -inner.x, inner.x), clamp(v.position.y, -inner.y, inner.y),
                     clamp(v.position.z, -inner.z, inner.z));
        const Vec3 d = v.position - q;
        maxDistErr = max2(maxDistErr, std::fabs(length(d) - r));
        maxNormalErr = max2(maxNormalErr, 1.0f - dot(normalize(d), v.normal));
        if (std::fabs(v.position.x) > he.x + 1e-5f || std::fabs(v.position.y) > he.y + 1e-5f ||
            std::fabs(v.position.z) > he.z + 1e-5f) {
            maxDistErr = 1e9f;  // outside the requested box
        }
    }
    report(maxDistErr < 1e-4f && maxNormalErr < 1e-4f,
           "m. rounded box lies on its distance field with exact normals",
           fmt("%u verts, max |dist-r| %.2e, max normal error %.2e", rb.vertexCount(),
               static_cast<double>(maxDistErr), static_cast<double>(maxNormalErr)));

    // ---- duplicated seam vertices must carry identical normals, otherwise a
    // visible shading line runs up every cylinder/sphere/capsule.
    struct SeamCase {
        const char* name;
        MeshData mesh;
    };
    std::vector<SeamCase> seams;
    seams.push_back({"makeUvSphere seam", makeUvSphere(1, 32, 16)});
    seams.push_back({"makeCylinder seam", makeCylinder(0.5f, 2, 32, true)});
    seams.push_back({"makeCapsule equator", makeCapsule(0.35f, 1.0f, 32, 8)});
    seams.push_back({"makeTorus seams", makeTorus(1, 0.35f, 48, 24)});
    for (SeamCase& sc : seams) {
        // Compare vertices that share a position.  A mismatch is only a defect if
        // it falls in the smooth band: the cylinder's cap rim is a deliberate
        // 90 degree crease and must NOT be smoothed away.
        std::vector<uint32_t> remap = weldByPosition(sc.mesh, 1e-5f);
        std::map<uint32_t, std::vector<uint32_t>> byWeld;
        for (uint32_t i = 0; i < sc.mesh.vertexCount(); ++i) byWeld[remap[i]].push_back(i);
        int groups = 0, creases = 0, seams = 0;
        float worstSeamAngle = 0.0f, worstSeamDot = 1.0f;
        for (const auto& kv : byWeld) {
            if (kv.second.size() < 2) continue;
            ++groups;
            for (size_t a = 0; a < kv.second.size(); ++a) {
                for (size_t b = a + 1; b < kv.second.size(); ++b) {
                    const float d = dot(sc.mesh.vertices[kv.second[a]].normal,
                                        sc.mesh.vertices[kv.second[b]].normal);
                    const float deg = std::acos(clamp(d, -1.0f, 1.0f)) * RAD2DEG;
                    if (deg > 40.0f) {
                        ++creases;  // deliberate hard crease, must stay hard
                    } else if (deg > 1.5f) {
                        ++seams;
                        if (deg > worstSeamAngle) {
                            worstSeamAngle = deg;
                            worstSeamDot = d;
                        }
                    }
                }
            }
        }
        std::printf("   %-22s %d coincident groups, %d hard creases, %d seam mismatches (worst %.3f deg)\n",
                    sc.name, groups, creases, seams, worstSeamAngle);
        report(seams == 0, fmt("m. %s has no shading seam at coincident vertices", sc.name),
               fmt("%d shared-position groups, %d intentional creases, worst smooth-band mismatch %.3f deg",
                   groups, creases, worstSeamAngle));
        (void)worstSeamDot;
    }
}

}  // namespace

int main() {
    std::printf("room2 procedural mesh tests\n");
    std::printf("=====================================================================\n");
    testA();
    testB();
    testC();
    testD();
    testE();
    testF();
    testG();
    testH();
    testI();
    testJ();
    testK();
    testL();
    testM();
    std::printf("=====================================================================\n");
    std::printf("%d checks, %d failures -> %s\n", g_checks, g_failures, g_failures == 0 ? "PASS" : "FAIL");
    return g_failures == 0 ? 0 : 1;
}
